# This is a basic workflow to help you get started with Actions
name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: windows-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      
      - name: Setup MSBuild Path
        uses: warrenbuckley/Setup-MSBuild@v1 
        
      - name: Setup NuGet
        uses: NuGet/setup-nuget@1.0.2
      #Compile app in release mode
      
      - name: Restore NuGet Packages
        run: nuget restore BankAccount.sln
      
      - name: Build app
        run: msbuild BankAccount.sln /p:Configuration=Release
      
      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: BankAccountApp
          path: BankAccount\bin\Release

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
